pool:
  vmImage: ubuntu-latest
stages:
  - stage: cibuild
    displayName: appcibuild
    jobs:
      - job: build
        displayName: cijob
        steps:
          - script: dotnet restore
            displayName: restorenugetpkg
          - script: dotnet build
            displayName: build .NET core
        

  - stage: Deploy
    displayName: release
    jobs: 
      - job: Deploy
        steps:
         - task: AzureRmWebAppDeployment@4
           inputs:
             ConnectionType: AzureRM
             azureSubscription: Pay-As-You-Go(049cc0b9-2696-4e70-871b-4366be487c19)
             appType: webApp
             WebAppName: spacegamepoc3357
             packageForLinux: $(system.ArtifactsDirectory)/drop/*.zip         
